# 3D Tensor Operations

## Based on "A Third-Order Generalization of the Matrix SVD as a Product of Third-Order Tensors" by Kilmer et al.

The following is an example of a 3-dimensional tensor:

In [1]:
import numpy as np
from numpy import array

T = array([
  [
   [1,2,3],    
   [4,5,6],    
   [7,8,9]
  ],
  [
   [11,12,13], 
   [14,15,16], 
   [17,18,19]
  ],
  [
   [21,22,23], 
   [24,25,26], 
   [27,28,29]
  ],
])

T

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In numpy, the first dimension corresponds to the *depth* associated with the tensor, the second dimension corresponds to the rows of the tensor, and the third dimension corresponds to the columns of the tensor:

In [2]:
T.shape

(3, 3, 3)

In other words, we can imagine the above tensor as a *number cube*, where its componenet matrices are stacked on top of each other going into the page.

Just as with vectors and matrices, we can define operations such as scalar multiplication and tensor addition on tensors. This allows us to define a vector space whose vectors are tensors. Such a vector space allows us to form linear combinations of tensors:

In [3]:
# scalar mulitiplication

T * 2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[22, 24, 26],
        [28, 30, 32],
        [34, 36, 38]],

       [[42, 44, 46],
        [48, 50, 52],
        [54, 56, 58]]])

In [4]:
# tensor addition (component-wise)

T + T

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[22, 24, 26],
        [28, 30, 32],
        [34, 36, 38]],

       [[42, 44, 46],
        [48, 50, 52],
        [54, 56, 58]]])

In [5]:
# tensor hadamard product (component-wise multiplication)

T * T

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[121, 144, 169],
        [196, 225, 256],
        [289, 324, 361]],

       [[441, 484, 529],
        [576, 625, 676],
        [729, 784, 841]]])

Given a tensor, we can obtain *sub-tensors* called *slices* and *fibers* by cutting the tensor in various ways.

A *slice* occurs when we fix all indices except two. 

In the case of a 3-dimensional tensor, we can obtain *frontal slices*, *horizontal slices* and *lateral slices*:

In [6]:
T = array(
    [1, 14, 15,
    23, 6, 20,
    24, 18, 8,

    15, 8, 7,
    28, 12, 17,
    21, 29, 23,

    9, 5, 13,
    7, 22, 26,
    21, 1, 19]).reshape((3, 3, 3))

T

array([[[ 1, 14, 15],
        [23,  6, 20],
        [24, 18,  8]],

       [[15,  8,  7],
        [28, 12, 17],
        [21, 29, 23]],

       [[ 9,  5, 13],
        [ 7, 22, 26],
        [21,  1, 19]]])

In [7]:
print('T:\n\n', T, '\n')
print('frontal slices of T:\n')
for i in range(3):
    print(T[i,:,:])
    print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

frontal slices of T:

[[ 1 14 15]
 [23  6 20]
 [24 18  8]]

[[15  8  7]
 [28 12 17]
 [21 29 23]]

[[ 9  5 13]
 [ 7 22 26]
 [21  1 19]]



In [8]:
print('T:\n\n', T, '\n')
print('horizontal slices of T:\n')
for i in range(3):
    print(T[:,i,:])
    print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

horizontal slices of T:

[[ 1 14 15]
 [15  8  7]
 [ 9  5 13]]

[[23  6 20]
 [28 12 17]
 [ 7 22 26]]

[[24 18  8]
 [21 29 23]
 [21  1 19]]



In [9]:
print('T:\n\n', T, '\n')
print('lateral slices of T:\n')
for i in range(3):
    print(T[:,:,i])
    print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

lateral slices of T:

[[ 1 23 24]
 [15 28 21]
 [ 9  7 21]]

[[14  6 18]
 [ 8 12 29]
 [ 5 22  1]]

[[15 20  8]
 [ 7 17 23]
 [13 26 19]]



A *fiber* occurs when we fix all indices except one:.

In this way, we can obtain *depth-fibers*, *row-fibers* and *column-fibers*:

In [10]:
print('T:\n\n', T, '\n')
print('mode-0 fibers of T (depth-fibers):\n')
for i in range(3):
    for j in range(3):
        print(T[:,i,j])
        print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

mode-0 fibers of T (depth-fibers):

[ 1 15  9]

[14  8  5]

[15  7 13]

[23 28  7]

[ 6 12 22]

[20 17 26]

[24 21 21]

[18 29  1]

[ 8 23 19]



In [11]:
print('T:\n\n', T, '\n')
print('mode-1 fibers of T (row-fibers):\n')
for i in range(3):
    for j in range(3):
        print(T[i,:,j])
        print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

mode-1 fibers of T (row-fibers):

[ 1 23 24]

[14  6 18]

[15 20  8]

[15 28 21]

[ 8 12 29]

[ 7 17 23]

[ 9  7 21]

[ 5 22  1]

[13 26 19]



In [12]:
print('T:\n\n', T, '\n')
print('mode-2 fibers of T (column-fibers):\n')
for i in range(3):
    for j in range(3):
        print(T[i,j,:])
        print()

T:

 [[[ 1 14 15]
  [23  6 20]
  [24 18  8]]

 [[15  8  7]
  [28 12 17]
  [21 29 23]]

 [[ 9  5 13]
  [ 7 22 26]
  [21  1 19]]] 

mode-2 fibers of T (column-fibers):

[ 1 14 15]

[23  6 20]

[24 18  8]

[15  8  7]

[28 12 17]

[21 29 23]

[ 9  5 13]

[ 7 22 26]

[21  1 19]



We can compress the above ideas into the following generalized functions:

In [13]:
def get_slices(T):
    '''given a tensor T, returns all of its slices.'''
    shape = T.shape
    depth = shape[0]
    rows = shape[1]
    columns = shape[2]
    
    result = []
    frontal_slices = []
    horizontal_slices = []
    lateral_slices = []
    
    # get frontal slices
    for i in range(depth):
        frontal_slices.append(T[i,:,:])
    result.append(frontal_slices)
    
    # get horizontal slices
    for i in range(rows):
        horizontal_slices.append(T[:,i,:])
    result.append(horizontal_slices)
    
    # get lateral slices
    for i in range(columns):
        lateral_slices.append(T[:,:,i])
    result.append(lateral_slices)
    
    return result

slices = get_slices(T)

In [14]:
slices[0]

[array([[ 1, 14, 15],
        [23,  6, 20],
        [24, 18,  8]]),
 array([[15,  8,  7],
        [28, 12, 17],
        [21, 29, 23]]),
 array([[ 9,  5, 13],
        [ 7, 22, 26],
        [21,  1, 19]])]

In [15]:
slices[1]

[array([[ 1, 14, 15],
        [15,  8,  7],
        [ 9,  5, 13]]),
 array([[23,  6, 20],
        [28, 12, 17],
        [ 7, 22, 26]]),
 array([[24, 18,  8],
        [21, 29, 23],
        [21,  1, 19]])]

In [16]:
slices[2]

[array([[ 1, 23, 24],
        [15, 28, 21],
        [ 9,  7, 21]]),
 array([[14,  6, 18],
        [ 8, 12, 29],
        [ 5, 22,  1]]),
 array([[15, 20,  8],
        [ 7, 17, 23],
        [13, 26, 19]])]

In [17]:
def get_fibers(T):
    '''given a 3D tensor T, returns all of its fibers.'''
    shape = T.shape
    depth = shape[0]
    rows = shape[1]
    columns = shape[2]
    
    result = []
    mode_0_fibers = []
    mode_1_fibers = []
    mode_2_fibers = []
    
    # get mode-0 fibers
    for i in range(rows):
        for j in range(columns):
            mode_0_fibers.append(T[:,i,j])
    result.append(mode_0_fibers)
    
    # get mode-1 fibers
    for i in range(depth):
        for j in range(columns):
            mode_1_fibers.append(T[i,:,j])
    result.append(mode_1_fibers)
    
    # get mode-2 fibers
    for i in range(depth):
        for j in range(rows):
            mode_2_fibers.append(T[i,j,:])
    result.append(mode_2_fibers)
    
    return result

In [18]:
fibers = get_fibers(T)

In [19]:
fibers[0]

[array([ 1, 15,  9]),
 array([14,  8,  5]),
 array([15,  7, 13]),
 array([23, 28,  7]),
 array([ 6, 12, 22]),
 array([20, 17, 26]),
 array([24, 21, 21]),
 array([18, 29,  1]),
 array([ 8, 23, 19])]

In [20]:
fibers[1]

[array([ 1, 23, 24]),
 array([14,  6, 18]),
 array([15, 20,  8]),
 array([15, 28, 21]),
 array([ 8, 12, 29]),
 array([ 7, 17, 23]),
 array([ 9,  7, 21]),
 array([ 5, 22,  1]),
 array([13, 26, 19])]

In [21]:
fibers[2]

[array([ 1, 14, 15]),
 array([23,  6, 20]),
 array([24, 18,  8]),
 array([15,  8,  7]),
 array([28, 12, 17]),
 array([21, 29, 23]),
 array([ 9,  5, 13]),
 array([ 7, 22, 26]),
 array([21,  1, 19])]

In [22]:
T = array([
    1, 4, 5,
    2, 8, 7,
    9, 5, 3,
    2, 6, 2,
    8, 1, 3,
    7, 5, 6]).reshape((2, 3, 3))

T

array([[[1, 4, 5],
        [2, 8, 7],
        [9, 5, 3]],

       [[2, 6, 2],
        [8, 1, 3],
        [7, 5, 6]]])

The ability to decompose a tensor into its fibers give us a way of transforming one tensor into several matrices. This operation is called the *mode-n matricization* of a tensor. 

mode-n matricization* of a tensor works by collecting all fibers associated with the tensor's nth mode into the columns of a matrix:

In [23]:
def matricize(T):
    '''turns the mode-n fibers of T into the columns of a matrix'''
    modes = len(T.shape)
    result = []
    fibers = get_fibers(T)
    for i in range(modes):
        result.append(np.vstack(fibers[i]).T)
    return result

In [24]:
print('T:\n\n', T, '\n')

matricize(T)

T:

 [[[1 4 5]
  [2 8 7]
  [9 5 3]]

 [[2 6 2]
  [8 1 3]
  [7 5 6]]] 



[array([[1, 4, 5, 2, 8, 7, 9, 5, 3],
        [2, 6, 2, 8, 1, 3, 7, 5, 6]]),
 array([[1, 4, 5, 2, 6, 2],
        [2, 8, 7, 8, 1, 3],
        [9, 5, 3, 7, 5, 6]]),
 array([[1, 2, 9, 2, 8, 7],
        [4, 8, 5, 6, 1, 5],
        [5, 7, 3, 2, 3, 6]])]

Matricization can be implemented more easily using the *tensorly* library:

In [25]:
import tensorly
import tensorly as tl

for i in range(3):
    print(tl.unfold(T, i))

[[1 4 5 2 8 7 9 5 3]
 [2 6 2 8 1 3 7 5 6]]
[[1 4 5 2 6 2]
 [2 8 7 8 1 3]
 [9 5 3 7 5 6]]
[[1 2 9 2 8 7]
 [4 8 5 6 1 5]
 [5 7 3 2 3 6]]


In contrast to matricization, the *unfold* operation collects all of a tensor's *frontal slices* into *one matrix*, one below the other: 

In [26]:
def unfold(T):
    '''unfolds a 3-dimensional tensor into one matrix using its frontal slices.'''
    frontal_slices = get_slices(T)[0]
    return np.vstack(frontal_slices)

print('T:\n\n', T, '\n')

unfold(T)

T:

 [[[1 4 5]
  [2 8 7]
  [9 5 3]]

 [[2 6 2]
  [8 1 3]
  [7 5 6]]] 



array([[1, 4, 5],
       [2, 8, 7],
       [9, 5, 3],
       [2, 6, 2],
       [8, 1, 3],
       [7, 5, 6]])

The *fold* operation is the inverse of the *unfold* operation, and converts a matrix back into its initial tensor form:

In [27]:
tl.base.fold(T, 0, (2, 3, 3))

array([[[1, 4, 5],
        [2, 8, 7],
        [9, 5, 3]],

       [[2, 6, 2],
        [8, 1, 3],
        [7, 5, 6]]])

In [28]:
tl.base.fold(unfold(T), 0, (2, 3, 3))

array([[[1, 4, 5],
        [2, 8, 7],
        [9, 5, 3]],

       [[2, 6, 2],
        [8, 1, 3],
        [7, 5, 6]]])

Conversion of a tensor into a one-dimensional vector is called *vectorization*:

In [29]:
def vectorize(T):
    return T.reshape(1, -1)

print('T:\n\n', T, '\n')

vectorize(T)

T:

 [[[1 4 5]
  [2 8 7]
  [9 5 3]]

 [[2 6 2]
  [8 1 3]
  [7 5 6]]] 



array([[1, 4, 5, 2, 8, 7, 9, 5, 3, 2, 6, 2, 8, 1, 3, 7, 5, 6]])

In the case of matrices, we can decompose one matrix into several matrices using the standard definition of matrix multiplication. 

In the case of tensors, matters are more complex, since there are many ways of multiplying two tensors. Each tensor multiplication method opens up new avenues of decomposition. However, only certain tensor multiplication methods generalize standard notions of linear algebra, such as the SVD.

One example of a tensor multiplication operation is the *n-mode product*. This can be used to decompose one tensor into a smaller *core tensor* and several matrix *factors*:

In [30]:
# number of columns in A must match number of modes in T
# Each mode-n fiber is multiplied by the matrix U

A = array([
    [1, 2, 3],
    [4, 5, 6]
])

tl.tenalg.mode_dot(T, A, 1)

array([[[32, 35, 28],
        [68, 86, 73]],

       [[39, 23, 26],
        [90, 59, 59]]])

In [31]:
mode_1_unfolded = tl.unfold(T, 1)
result = A @ mode_1_unfolded

print('A:\n\n', A)
print('\nmode 1 unfolded:\n\n', mode_1_unfolded)
print('\nA times mode 1 unfolded:\n\n', result)
print('\nmode-1 tensor product:\n')
tl.base.fold(result, 1, (2, 2, 3))

A:

 [[1 2 3]
 [4 5 6]]

mode 1 unfolded:

 [[1 4 5 2 6 2]
 [2 8 7 8 1 3]
 [9 5 3 7 5 6]]

A times mode 1 unfolded:

 [[32 35 28 39 23 26]
 [68 86 73 90 59 59]]

mode-1 tensor product:



array([[[32, 35, 28],
        [68, 86, 73]],

       [[39, 23, 26],
        [90, 59, 59]]])

In [32]:
A = array([1, 2, 3])
tl.tenalg.mode_dot(T, A, 2).T

array([[24, 20],
       [39, 19],
       [28, 35]])

In [33]:
from tensorly.decomposition import tucker

tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

core, factors = tucker(tensor, rank=[2, 3])

print('core shape:\n', core.shape)
print('\nfactor shapes:')
print([f.shape for f in factors])

factor_0 = factors[0]
factor_1 = factors[1]

prod_1 = tl.tenalg.mode_dot(core, factor_0, 0)
prod_2 = tl.tenalg.mode_dot(prod_1, factor_1, 1)

print('\nreconstructed tensor:')

np.abs(np.round(prod_2, 2))

core shape:
 (2, 3)

factor shapes:
[(12, 2), (12, 3)]

reconstructed tensor:


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

The inner product between two tensors can be computed by vectorizing each tensor and computing the corresponding dot product:

In [34]:
def inner_product(T1, T2):
    vectorized_t1 = T1.reshape(1, -1)
    vectorized_t2 = T2.reshape(1, -1)
    return np.inner(vectorized_t1, vectorized_t2)[0][0]
             
print('T:\n\n', T, '\n')
print('Inner Product of T with T:\n\n', inner_product(T, T), '\n')

T:

 [[[1 4 5]
  [2 8 7]
  [9 5 3]]

 [[2 6 2]
  [8 1 3]
  [7 5 6]]] 

Inner Product of T with T:

 502 



We can bootstrap a norm out of an inner product as follows:

In [35]:
def norm(T):
    return np.sqrt(inner_product(T, T))

print('T:\n\n', T, '\n')
print('Norm of T:\n\n', norm(T), '\n')

T:

 [[[1 4 5]
  [2 8 7]
  [9 5 3]]

 [[2 6 2]
  [8 1 3]
  [7 5 6]]] 

Norm of T:

 22.40535650240808 



A square matrix in which each row (after the first) has the elements of the previous
row shifted cyclically one place to the right, is called a *circulant matrix*. 

A circulant matrix has a *multi-diagonal* structure, with elements on each diagonal having the same value.

Because each row of a circulant matrix has the same elements, we can define an operation that converts a vector into a circulant matrix as follows:

In [36]:
def circ(vector):
    n = vector.size
    C = np.empty((n, n))

    for i in range(n):
        C[i, i:] = vector[:n-i]
        C[i, :i] = vector[n-i:]  
    return C

v = array([1, 2, 3])
circ(v)

array([[1., 2., 3.],
       [3., 1., 2.],
       [2., 3., 1.]])

Circulant matrices have the following interesting properties:

1. The transpose of a circulant matrix is a circulant matrix.
2. The sum of two circulant matrices is a circulant matrix.
3. The product of two circulant matrices is a circulant matrix.
4. The product of two circulant matrices does not depend on order.

In [37]:
C = circ(v)

C.T

array([[1., 3., 2.],
       [2., 1., 3.],
       [3., 2., 1.]])

In [38]:
C + C

array([[2., 4., 6.],
       [6., 2., 4.],
       [4., 6., 2.]])

In [39]:
C @ C

array([[13., 13., 10.],
       [10., 13., 13.],
       [13., 10., 13.]])

In [40]:
C @ C.T == C.T @ C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Given a list of n x n matrices, we can apply the same idea to obtain a *block circulant matrix*:

In [41]:
def circ_block(matrices):
    shape = matrices[0].shape
    columns = shape[1]
    n = len(matrices)
    result = []
    
    for i in range (n):
        beginning = matrices[n-i:]
        end = matrices[:n-i]

        if not beginning:
            row = np.hstack(end)
        elif not end:
            row = np.hstack(beginning)
        else:
            row = np.hstack(beginning + end)
        result.append(row)
    return np.vstack(result)

M1 = np.eye(2) 
M2 = np.zeros((2, 2))
matrices = [M1, M2, M1]

circ_block(matrices)

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.]])

In the case of tensors, it turns out to be useful to shift by column instead of by row:

In [42]:
def block_circ_columns(matrices):
    shape = matrices[0].shape
    columns = shape[1]
    n = len(matrices)
    result = []
    
    for i in range (n):
        beginning = matrices[n-i:]
        end = matrices[:n-i]

        if not beginning:
            column = np.vstack(end)
        elif not end:
            column = np.vstack(beginning)
        else:
            column = np.vstack(beginning + end)
        result.append(column)
    return np.hstack(result)

M1 = np.eye(2) 
M2 = np.zeros((2, 2))
matrices = [M1, M2, M1]
block_circ_columns(matrices)

array([[1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.]])

Given one tensor, we can form a block circulant matrix from its frontal slices. 
However, instead of shifting by row, we shift by column:

In [43]:
def bcirc(T):
    frontal_layers = get_slices(T)[0]
    return block_circ_columns(frontal_layers)

bcirc(T)

array([[1, 4, 5, 2, 6, 2],
       [2, 8, 7, 8, 1, 3],
       [9, 5, 3, 7, 5, 6],
       [2, 6, 2, 1, 4, 5],
       [8, 1, 3, 2, 8, 7],
       [7, 5, 6, 9, 5, 3]])

We can use the `bcirc` and `unfold` operations to define a tensor-multiplication called `t-prod`, which allows us to generalize the standard SVD.

Given a tensor T1 with dimensions (l, m, n) and a tensor T2 with dimensions (m, o, n), the `t-prod` operation returns a third tensor with dimensions (l, o, n):

In [44]:
def t_prod(T1, T2):
    shape = T1.shape
    m1 = bcirc(T1)
    m2 = unfold(T2)
    product = m1 @ m2
    return tl.base.fold(product, 0, shape)

T3 = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

t_prod(T3, T3)

array([[[1830, 1938, 2046],
        [2208, 2343, 2478],
        [2586, 2748, 2910]],

       [[1830, 1938, 2046],
        [2208, 2343, 2478],
        [2586, 2748, 2910]],

       [[ 930, 1038, 1146],
        [1308, 1443, 1578],
        [1686, 1848, 2010]]])

To obtain a generalization of the SVD, we must also define a useful transpose operations on tensors, which allows us to also define the notion of *orthogonal tensors*.

If T is a tensor with dimensions (n1, n2, n3), then $A^T$ is the tensor with dimensions (n2, n1, n3) obtained by transposing each of the frontal slices of T and then reversing the order of transposed frontal slices 2 through n3:

In [45]:
def transpose(T):
    shape = T.shape
    frontal_slices = get_slices(T)[0]
    first_slice = frontal_slices[0]
    remaining_slices = frontal_slices[1:]
    reversed_remaining_slices = remaining_slices[::-1]

    result = []
    result.append(first_slice.T)
    
    for slice in reversed_remaining_slices:
        result.append(slice.T)
    return tl.base.fold(result, 0, shape)

print('T3:\n\n', T3, '\n')
transpose(T3)

T3:

 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 



array([[[ 1,  4,  7],
        [ 2,  5,  8],
        [ 3,  6,  9]],

       [[21, 24, 27],
        [22, 25, 28],
        [23, 26, 29]],

       [[11, 14, 17],
        [12, 15, 18],
        [13, 16, 19]]])

An *identity tensor* is a tensor whose first frontal slice is the identity matrix and whose other frontal slices are all zero matrices:

In [46]:
I = array([
  [
    [1, 0, 0],    
    [0, 1, 0],    
    [0, 0, 1]
  ],
  [
    [0, 0, 0], 
    [0, 0, 0], 
    [0, 0, 0]
  ],
  [
    [0, 0, 0], 
    [0, 0, 0], 
    [0, 0, 0]
  ],
])

We can use the above definition of the identity tensor to define the notion of a *tensor inverse*. The *inverse* of a tensor T is the tensor $T^{-1}$ such when T is multiplied by $T^{-1}$ using the `t-prod` operation, the identity tensor is obtained.

Tensor T1 is *orthogonal* to tensor T2 if multiplication of the two tensors under the `t-prod` operation in either order yields the identity tensor.

Orthogonal tensors generalize the notion of orthogonal matrices in the sense that the tensor norm is invariant under multiplication by an orthogonal tensor.

The last definition we need before defining the `t-SVD` is that of an `f-diagnoal` tensor. A tensor is *f-diagonal* if each of its frontal slices is a diagonal matrix. 

The `t-SVD` theorem states that any tensor T of dimensions (n1, n2, n3) can be factored as:

$T = USV{^T}$,

where U has dimensions (n1, n1, n3), V has dimensions (n2, n2, n3), S has dimensions (n1, n2, n3), both U and V are orthogonal tensors, and S is an *f-frontal* tensor.